config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'courses/index'

  resources :courses
  resources :videos
  resources :blogs
  resources :leads

  devise_for :users

  get 'errors/file_not_found'
  get 'errors/unprocessable'
  get 'errors/internal_server_error'

  match '/404', to: 'errors#file_not_found', via: :all
	match '/422', to: 'errors#unprocessable', via: :all
	match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_attached_file :image, styles: { medium: "300x300#", thumb: "C100x100#" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  has_many :videos
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/lead.rb
class Lead < ActiveRecord::Base
	validates :name, :email, :message, presence: true
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  	def configure_permitted_parameters
  		devise_parameter_sanitizer.for(:sign_up) << :name
  		devise_parameter_sanitizer.for(:account_update) << :name
  	end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :author, :stdesc, :category)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

	def index
		@courses = Course.all
	end

	def show
	end

	def new
		@course = Course.new
	end

	def create
		@course = Course.create(course_params)

		respond_to do |format|
      if @course.save
        format.html { redirect_to @course }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
	end

	def edit
	end

	def update
		respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
	end

	def destroy
		@course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
	end

	private

	def set_course
    @course = Course.friendly.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:name, :description, :image, :stdesc, :title, :sales_message, :characteristics, :stdesc, :testimonial)
  end

	
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def file_not_found
  end

  def unprocessable
  end

  def internal_server_error
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
	before_action :set_lead, only: [:show, :edit, :update, :destroy]

	def index
		@lead = Lead.all
	end

	def new
	end

	def create
		@lead = Lead.new lead_params
		if @lead.save
			redirect_to root_path, notice: "Thanks for the message! One of our guys will reach out to you soon."
			LeadMailer.new_lead(@lead).deliver_now
		else
			redirect_to root_path, alert: "Oops! We weren't able to save your information. Give it another try."
		end
	end

	def destroy
	  @lead.destroy
	  respond_to do |format|
	    format.html { redirect_to leads_url, notice: 'Lead was successfully deleted.' }
	    format.json { head :no_content }
	  end
	end

	private

	def set_lead 
		@lead = Lead.find(params[:id])
	end

	def lead_params
		params.require(:lead).permit(:name, :email, :telephone, :message)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		@lead = Lead.new
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "Short Description" %><br>
    <%= f.text_field :stdesc %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<section>
	<div class="container">
		<h1>Editing Blog</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @blog %> |
		<%= link_to 'Back', blogs_path %>
	</div>
</section>

app/views/blogs/index.html.erb
<section>
  <div class="col-md-8 col-md-offset-2">
    <select id="blogs">
      <option value='ALL' selected="selected">Todos</option>
      <option value="Rails">Rails</option>
      <option value="HTML">HTML</option>
      <option value="JS">Javascript</option>
      <option value="CSS">CSS</option>
    </select>
    <div id="blogs">
      <div class="heading">
        <h4>BLOG FOR QUICK LEARNING</h4>
      </div>
    
      <% @blogs.each do |blog| %>
        <div class="blog">
          <h2><%= link_to blog.title, blog %></h2>
          <p>
            <%= blog.stdesc.truncate(200) %>
          </p>
          <p>
            <%= link_to "Read more", blog %>
          </p>
          
          <ul class="blogDetails list-inline list-unstyled">
            <li><i class="fa fa-user"></i> <%= blog.author %></li>
            <li><i class="fa fa-calendar"></i> <%= blog.created_at %></li>
            <li><i class="fa fa-comment-o"></i> Comments</li>
          </ul>
          <% if user_signed_in? && current_user.admin == true %>
            <%= link_to 'Show', blog, class: "btn btn-default" %>
            <%= link_to 'Edit', edit_blog_path(blog), class: "btn btn-info" %>
            <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          <% end %>
          <span class="spec"><%= blog.category %></span>
        </div>
      <% end %>
    </div>
    <% if user_signed_in? && current_user.admin == true %>
        <%= link_to 'New Blog', new_blog_path, class: "btn btn-info btn-lg" %>
      <% end %>
  </div>
</section>

app/views/blogs/new.html.erb
<section>
	<div class="container">
		<h1>New Blog</h1>

		<%= render 'form' %>

		<%= link_to 'Back', blogs_path %>
	</div>
</section>

app/views/blogs/show.html.erb
<section>
  <div class="col-md-8 col-md-offset-2">
  	<div id="blogs">
      <div class="heading">
        <h4>BLOG FOR QUICK LEARNING</h4>
      </div>
  		<div class="blog" style="border-bottom: none;">
        <h2><%= link_to @blog.title, @blog %></h2>
        <ul class="blogDetails list-inline list-unstyled">
          <li><i class="fa fa-user"></i> <%= @blog.author %></li>
          <li><i class="fa fa-calendar"></i> <%= @blog.created_at %></li>
          <li><i class="fa fa-comment-o"></i> Comments</li>
        </ul>
        <%= raw(@blog.body) %>
        <hr>
        <div class="row">
        	<div class="col-sm-2">
            <%= image_tag("nate.jpg", class: "img-responsive rounded small-img") %>
  		     </div>
  		     <div class="col-sm-10">
  		      <div class="row">
              <div class="col-xs-6">
  		          <h3><%= @blog.author %></h3>
              </div>
  		        <div class="col-xs-6" style="text-align: right;">
                <%= link_to "http://www.twitter.com/nallenanderson", target: "_blank", class: "blog-fa" do %>
      		        <span class="fa-stack fa-lg text-center">
      						  <i class="fa fa-square-o fa-stack-2x"></i>
      						  <i class="fa fa-twitter fa-stack-1x"></i>
      						</span>
                <% end %>
                <%= link_to "http://www.github.com/nallenanderson", target: "_blank", class: "blog-fa" do %>
      						<span class="fa-stack fa-lg text-center">
      						  <i class="fa fa-square-o fa-stack-2x"></i>
      						  <i class="fa fa-github fa-stack-1x"></i>
      						</span>
                <% end %>
                <%= mail_to "nallenanderson@gmail.com", class: "blog-fa" do %>
      						<span class="fa-stack fa-lg text-center">
      						  <i class="fa fa-square-o fa-stack-2x"></i>
      						  <i class="fa fa-envelope fa-stack-1x"></i>
      						</span>
                <% end %>
              </div>
            </div>
  						
  		        <p class="author">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  		        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>
  		      
  		     </div>
        </div>
        <hr>

        <div id="disqus_thread"></div>

        <% if user_signed_in? && current_user.admin == true %>
          <%= link_to 'Show', @blog, class: "btn btn-default" %>
          <%= link_to 'Edit', edit_blog_path(@blog), class: "btn btn-info" %>
          <%= link_to 'Destroy', @blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        <% end %>
      </div>

  	</div>
  </div>
</section>

<script type="text/javascript">
  /* * * CONFIGURATION VARIABLES * * */
  var disqus_shortname = 'natemodyo';
  
  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %> 
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this month from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel-group panel-default">
    <div class="form-group">
      <%= f.label :name, "Nombre del Curso" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label "Descripción Breve" %> <small> (Para la página Index)</small>
      <%= f.text_field :stdesc, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label "Título" %> <small>(Puedes incluir HTML)</small>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label "Mensaje" %> <small>(Puedes incluir HTML)</small>
      <%= f.text_field :sales_message, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description, "Descripción" %> <small>(Puedes incluir HTML)</small>
      <%= f.text_field :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label "Características" %> <small>(Puedes incluir HTML)</small>
      <%= f.text_field :characteristics, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label "Testimoniales" %> <small>(Puedes incluir HTML)</small>
      <%= f.text_field :testimonial, class: "form-control" %>
    </div>

    <div class="actions">
      <%= f.submit "Guardar", class: "btn btn-lg btn-info" %>
      <%= link_to 'Cancelar', courses_path, class: "btn btn-lg btn-danger pull-right" %>
    </div>
  </div><!-- PANEL-GROUP -->
<% end %>

app/views/courses/edit.html.erb
<section>
	<div class="container">
		<h1>Editar Curso</h1>
		<%= render 'form' %>
	</div>
</section>

app/views/courses/index.html.erb
<section id="intro">
	<div id="vidback">
		<video id="video_background" src="https://d2p52n04yb9sso.cloudfront.net/uploads/42522b70e53b11e48d4cb12604e0c5a7/mp4/doors.mp4" autoplay loop>
	</div>
	 <div class="overlay"></div>
   <div class="intro-body">
  		<p>Santiago-based web development.</p>
   </div> 
</section>

<section id="about"> 
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<p class="lead">
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
				</p>
			</div>
		</div>
	</div>
</section>

<section id="course">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<div class="row">
					<% @courses.each do |course| %>
						<div class="col-md-4">
			    		<div class="boxes">
			    			<div class="top">
			    				<h3><%= link_to course.name, course %></h3>
			    			</div>
			    			<p><%= course.stdesc %></p>
			    			<%= link_to "Ver Más", course, class: "btn btn-lg btn-green" %><br>
						    <% if user_signed_in? && current_user.admin == true %>
							    <%= link_to 'Show', course, class: 'btn btn-info' %>
							    <%= link_to 'Edit', edit_course_path(course), class: 'btn btn-primary' %>
							    <%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
							  <% end %>
							</div>
						</div>
				  <% end %>

				  <% if user_signed_in? && current_user.admin == true %>
			  		<%= link_to "Create Course", new_course_path, class: 'btn btn-default' %>
			  	<% end %>

				</div>
			</div>
		</div>
	</div>
</section>

app/views/courses/new.html.erb
<section>

	<div class="container">

		<h1>Crear un curso</h1>

		<%= render 'form' %>

	</div>

</section>

app/views/courses/show.html.erb
<section class="main">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<p><%= @course.title%></p>
			</div>
		</div>
	</div>
</section>

<section class="courses">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<p class="lead"><%= raw(@course.sales_message) %></p>
			</div>
		</div>
	</div>
</section>

<section id="course-description">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2 hider">
				<h1><%= @course.name %></h1>
				<p class="lead hideme"><%= @course.description %></p>
			</div>

			<div class="clearfix"></div><hr />

			<div class="col-md-8 col-md-offset-2 hider">
				<div class="row">
					<div class="hideme">
						<%= raw(@course.characteristics) %>
					</div>
				</div>
			</div>

			<div class="clearfix"></div><hr />

			<div class="col-md-8 col-md-offset-2">
				<div class="row">
					<div class="col-md-12 hider">
						<h2>¿Qué dicen nuestros estudiantes?</h2>
						<div class="hideme">
							<%= raw(@course.testimonial) %>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
</section>

<section id="sign-up">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<div class="row">
					<div class="col-sm-7">
						<h2>Aprende ahora!</h2>
					</div>
					<div class="col-sm-5">
						<%= link_to "Empezar Right Now!", course_path, class: "btn btn-lg btn-block" %>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<% if user_signed_in? && current_user.admin == true %>
	<div class="container">
		<div class="row">
			<div class="col-md-9 col-md-offset-2">
				<%= link_to "Edit", edit_course_path(@course), class: "btn btn-lg btn-info" %>
			</div>
		</div>
	</div>
<% end %>

<script>
	$('.main').css('min-height',$(window).height()-50);
</script>

app/views/layouts/_footer.html.erb
<footer>
	<div class="container-fluid">
		<div class="col-sm-8 col-sm-offset-2 text-center">
			<small>&copy; 2017 devocode, llp</small>
	</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="col-sm-8 col-sm-offset-2">
    <!-- <div class="container-fluid"> -->
      <!-- Brand and toggle get grouped for better mobile display -->

      <div class="navbar-header">
        <button type="button" id="right-menu" class="navbar-toggle" data-toggle="collapse" href="#sidr-right">
          <%= image_tag('bars.png', class: "img-responsive bars")%>
        </button>

        <%= link_to root_path do %>
          <%= image_tag("devocode-logo1.png", class: "img-responsive") %>
        <% end %>
      </div>

      <div id="sidr-right">
         <ul>
            <li><%= link_to "Process", "#" %></li>
            <li><%= link_to "News", blogs_path %></li>
  
            <% if user_signed_in? %>
              <li><%= link_to "My Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Clients", user_session_path %></li>
              <li><%= link_to "Contact", new_user_registration_path %></li>
            <% end %>
         </ul>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse">
        
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Process", "#" %></li>
          <li><%= link_to "News", blogs_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "My Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li class="lastone"><%= link_to "Clients", user_session_path %></li>
            <li><%= link_to "Contact", new_user_registration_path, class: "btn btn-sign" %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    <!--</div> /.container-fluid -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Connected web development for Rails, Angular, Ember, and mobile projects.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="google-site-verification" content="PJpvafTqkpBgtY8X08LxMbbkAjbhffEq9B-mfeoGjbE" />
</head>
<body>

<%= render 'layouts/header' %>

<% flash.each do |name, msg| %>
	<div class="container">	
		<%= content_tag(:div, msg, class: "alert alert-dismissible fade in") do %>
			<div class="container">
				<%= msg %>
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
			</div>
		<% end %>
	</div>
<% end %>

<%= yield %>
<div class="clearfix"></div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/home.html.erb
<div id="particles-js"></div>

<section id="hello">
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-8 col-sm-offset-2">
				<h1>Connected</h1>
				<h2>development</h2>
				<p class="lead">Helping clients connect the dots between ideas, design, development and deployment.</p>
				<%= link_to "Our Process", "#follower", class: "btn btn-lg btn-trans one page-scroll" %>
			</div>
		</div>
	</div>
</section>

<section id="us">
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-8 col-sm-offset-2">
				<div class="row">
					<div class="col-md-7">

						<h4>SIMPLY STATED:</h4>
						<p>We are <span class="call one">designers and developers</span>. We <span class="call two">love web development</span>. From idea <span class="call one">validation</span> to product <span class="call one">deployment</span>, let us help you <span class="call two">connect the dots</span>.</p>
					</div>
					<div class="col-md-5">
						<%= image_tag("comp.png", class: "img-responsive")%>
					</div>
				</div>

			</div>
		</div>
	</div>
</section>

<section id="do">
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-8 col-sm-offset-2">

				<h2 class="text-center">This is what we do.</h2>

				<div class="row text-center does">
					<div class="col-xs-3">
						<%= image_tag('responsive.png', class: 'img-responsive') %>
						<h4>Site Design</h4>
					</div>
					<div class="col-xs-3">
						<%= image_tag('ruby.png', class: 'img-responsive') %>
						<h4>Ruby on Rails</h4>
					</div>
					<div class="col-xs-3">
						<%= image_tag('reactjs.png', class: 'img-responsive') %>
						<h4>React JS</h4>
					</div>
					<div class="col-xs-3">
						<%= image_tag('apps.png', class: 'img-responsive') %>
						<h4>Mobile Apps</h4>
					</div>
				</div>

			</div>
		</div>
	</div>
</section>

<section id="follower">
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-8 col-sm-offset-2">
				<div class="row">
					<h2 class="text-center">We follow a <span class="callout red">simple</span> and <span class="callout green">transparent</span> process.</h2>
					<div class="col-md-4">
						<div class="boxes">
							<div class="top blue">
								<%= image_tag("define.png", class: "img-responsive pull-right")%>
		    				<h3>Define</h3>
		    			</div>
		    			<p>Building the right thing can be hard, so we invest the time up-front to define the project, scope and features to provide real value.</p>
		    			<div class="container-fluid">
		    				<a class="btn btn-block black">What to Define ?</a>
		    			</div>
						</div>
					</div>

					<div class="col-md-4">
						<div class="boxes">
							<div class="top yellow">
								<%= image_tag("develop.png", class: "img-responsive pull-right")%>
		    				<h3>Develop</h3>
		    			</div>
		    			<p>After defining the project, we'll jump right in. We have a favorite tech stack, but are flexible to use technologies and tools to fit your needs.</p>
		    			<div class="container-fluid">
		    				<a class="btn btn-block black">How to Develop ?</a>
		    			</div>
						</div>
					</div>

					<div class="col-md-4">
						<div class="boxes">
							<div class="top green">
								<%= image_tag("deploy.png", class: "img-responsive pull-right")%>
		    				<h3>Deploy</h3>
		    			</div>
		    			<p>Once the project has been successfully built, tested and approved, we'll help you get it deployed using scalable services to fit your needs.</p>
		    			<div class="container-fluid">
		    				<a class="btn btn-block black">Where to Deploy ?</a>
		    			</div>
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>
</section>

<div class="clearfix"></div>

<section id="nexter">
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-8 col-sm-offset-2">
				<h2>Enough about us. Let's talk about you...</h2>
				<p class="lead">We want to know what we can do to make your project a success. Get in touch so we can help you build something awesome.</p>
				<%= form_for Lead.new, class: "inline" do |f| %>
				  <div class="row">
				    <div class="form-group col-md-4">
				      <label>Name</label>
				      <%= f.text_field :name, class: "form-control", placeholder: "Your name...", required: true %>
				    </div>
				    <div class="form-group col-md-4">
				      <label>Email</label>
				      <%= f.email_field :email, class: "form-control", placeholder: "Your email...", required: true %>
				    </div>
				    <div class="form-group col-md-4">
				      <label>Telephone</label>
				      <%= f.text_field :telephone, class: "form-control", placeholder: "Your phone..." %>
				    </div>
				  </div>
				  <div class="form-group">
				    <label>Message:</label>
				    <%= f.text_area :message, rows: "4", class: "form-control", placeholder: "Tell us about you, your project, or anything else here...", required: true %>
				  </div>
				  <%= button_tag class: "btn btn-lg btn-trans two pull-right" do %>
				  	Contact Us
				  <% end %>
				<% end %>


			</div>
		</div>
	</div>
</section>